### ISSUE TITLE
Hey，some issues about usb port...

### ISSUE THREAD

**Issue by bk210** [Spectrelai/Hackintosh-B460M-MORTAR-WIFI#2]
大佬，你好。非常感谢efi，但是我试了后面的3个usb3.0的口，都没有办法使用。plist使用的是6600xt的版本，请问是您这边正常使用吗？激活的是哪一个usb呢？

**Comment by Spectrelai** [comment]
因为有15个端口限制，我的机箱前面板需要usb3.0 x 3，所以把后面板的两个usb3.0阉割了，后面的c口旁边的3.0 a口在我这里是可以正常用的。
机箱不一样对接口的需求也不同，你可以考虑重新定制usb，不难的，具体可以参考[这个链接](https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html)

**Comment by bk210** [comment]
好的，多谢回复👌

**Comment by Spectrelai** [comment]
> 好的，多谢回复👌

我测试了下，在12.2下USB3.0我的也全都失效了，重新加回[XHCI-unsupported.kext](https://github.com/Spectrelai/Hackintosh-B460M-MORTAR-WIFI/tree/main/EFI/OC/Kexts/XHCI-unsupported.kext)后就正常了

现在这个问题已经更新解决了，顺便在README里加上了USB定制的简单说明，整理了这个主板的USB端口表，可以参照下

**Comment by bk210** [comment]
好的好的，我到时候试试！实在是太负责任了😭
