### ISSUE TITLE
请问机箱前置USB接口是如何定制？有几个usb2.0，几个3.0

### ISSUE THREAD

**Issue by tuhping** [Spectrelai/Hackintosh-B460M-MORTAR-WIFI#5]

**Comment by Spectrelai** [comment]
3个完整USB3.0，2个A口，1个C口
具体可以看此处[说明](https://github.com/Spectrelai/Hackintosh-B460M-MORTAR-WIFI#usb%E5%AE%9A%E5%88%B6)，表中除去默认屏蔽的端口就是默认的定制
