### ISSUE TITLE
有些问题需要澄清

### ISSUE THREAD

**Issue by fowlmouse** [Spectrelai/Hackintosh-B460M-MORTAR-WIFI#6]
大佬：  

我是用其他人版本的EFI opencore 0.7.4 目前12.2 版本正常 目前系统配置：

配置 | 型号
-- | --
CPU | I5-10400
主板 | B460M 迫击炮 WIFI
内存 | 三星 2666 32G*2
显卡 | 蓝宝 AMD Radeon RX 5700 XT 8 GB
BIOS | VMW71.00V.18452719.B64.2108091906

以下几个问题请教一下：
1. 我看了USB端口对应 实在搞不明白HS&SS 差别 ,并且有些端口对应 对不上号 请参阅图
2. 默认屏蔽：HS11, HS12, SS01, SS02 ： 意思是这些端口都没法用是吗？ 也就是C口没功能 + USB2.0 端口没功能?
3. 我是苹果免驱网卡 并且蓝牙供电 ＂JUSB2" & 机箱USB2 插口 接在"JUSB1" 如果没功能 是否表示蓝牙日后插在上面没功能？
4. 当前您的"config.rx6600xt.plist" 是否可以直接沿用不需要更改？
5.  当前图档标示 请确认是否有误 并且补齐我找不到的 （HS08/HS11/HS12）然后我可以修改成当下对应0.7.8的版本 并更新出来
6. 一个建议 ＂硬件测试配置＂ 欠缺BIOS 版本 请添加
 问题稍多 请您耐心解答 谢谢

<img width="1099" alt="1" src="https://user-images.githubusercontent.com/64547651/160170045-b905ebb8-fe67-4cc9-9910-288347c9d648.png">
<img width="1482" alt="2" src="https://user-images.githubusercontent.com/64547651/160170054-4bfc853a-0c50-41d4-a6fd-073d82bb44c9.png">
档

**Comment by Spectrelai** [comment]
1.macOS中USB2.0和USB3.0是分开的两个端口，所以物理的USB3.0插口其实在macOS里会有两个对应，一个是HS（USB2.0），另一个是SS（USB3.0）。HS08是内置WIFI网卡的蓝牙端口（走USB通道），主板上没有对应，所以如果你不用板载网卡的话就不需要定制HS08。同样的HS12也是内置的，主板上没有插口关联，macOS下微星的灯效控制我没找到有软件做了适配，所以也是可以屏蔽掉。然后HS11是一个内置的Hub口，JUSB1和JUSB2引出来的USB口都是从HS11扩展出来的，我的机箱没有2.0的口，所以我就屏蔽了HS11
2.默认屏蔽这几个是我不需要用到JUSB1-2，微星灯效。还有就是你的第二个图的4的那两个USB3.0口阉割了3.0的功能，只作为2.0使用（屏蔽SS01,SS02,保留HS01,HS02）
3.是的，对于你的情况来说不能屏蔽HS11
4.可以沿用，但需要填充你的三码，5000系和6000系A卡配置是一样的，我之前就是用的5500XT
5.如1所述，HS11对应JUSB1和JUSB2两个插口，HS08和HS12是内置的通道，给主板的蓝牙和灯效使用的，没有插口对应
6.下一版会增加
