### ISSUE TITLE
请教一下，如何保留ax200加装免驱网卡？

### ISSUE THREAD

**Issue by pv0402** [Spectrelai/Hackintosh-B460M-MORTAR-WIFI#8]
Ax200想留给双系统win用，mac下用m2或者pcie转免驱网卡，是不是只要oc屏蔽ax200的pcie再去掉wifi蓝牙驱动就行了呀？不涉及到别的通道吧？

**Comment by pv0402** [comment]
看了下usb定制说明，蓝牙要走usb通道会不会冲突或者屏蔽之后ax200和免驱网卡都不能用呀？免驱卡是94360cs2

**Comment by Spectrelai** [comment]
ax200的蓝牙走的usb通道是固定的，不放intel的wifi蓝牙驱动就行了，推测应该不会冲突。蓝牙usb可以先加入usb定制，如果没影响就最好了，因为屏蔽了的话用oc引导win会一样没有内置蓝牙

**Comment by pv0402** [comment]
> ax200的蓝牙走的usb通道是固定的，不放intel的wifi蓝牙驱动就行了，推测应该不会冲突。蓝牙usb可以先加入usb定制，如果没影响就最好了，因为屏蔽了的话用oc引导win会一样没有内置蓝牙

好的好的 感谢！
